# Imagem base com Python
FROM python:3.11-slim

# Diretório dentro do container
WORKDIR /app

# Copia os arquivos do projeto para o container
COPY . .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expõe a porta que o Flask usa
EXPOSE 5000

# Comando para rodar o servidor Flask
CMD ["python", "run.py"]

